name: PR 5037 Python validation

permissions:
  contents: read

on:
  push:
    branches:
      - validation/pr-5037-pytest

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Common setup
        uses: ./.github/actions/common-setup
        with:
          python-version: "3.13"
          free-disk-space: "true"
          free-disk-space-max-build: "true"
          build-type: "test"
          rust-cache-enabled: "false"

      - name: Run Python tests
        run: make pytest
